[variables]
main_domain = "${domain}"
postgres_password = "${password:32}"
folio_secret = "${hash:64}"

[[config.domains]]
serviceName = "folio"
port = 4870
host = "${main_domain}"

[config.env]
PUBLIC_URL = "https://${main_domain}"
POSTGRES_PASSWORD = "${postgres_password}"
FOLIO_SECRET = "${folio_secret}"
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
GOOGLE_ALLOWED_DOMAINS = ""
CURSOR_API_KEY = ""
