/**
 * Per-space git tokens (round 3): stored ONLY in data/system/git-credentials.json
 * (chmod 600), never in PG, never in the clone's own .git/config, never logged.
 * Fed to git via a generated GIT_ASKPASS helper (data/system/askpass.mjs) that
 * reads FOLIO_GIT_SPACE from its own environment (set per-invocation by
 * server/git.ts) to look up the right token — the only thing that ever
 * touches the token besides this file is that one child-process env var.
 */
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const AUTH_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../data/system');
const CREDENTIALS_FILE = path.join(AUTH_DIR, 'git-credentials.json');
export const ASKPASS_SCRIPT = path.join(AUTH_DIR, 'askpass.mjs');

type CredentialsFile = Record<string, { token: string }>;

async function readCredentials(): Promise<CredentialsFile> {
  try {
    return JSON.parse(await fs.readFile(CREDENTIALS_FILE, 'utf8')) as CredentialsFile;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return {};
    throw err;
  }
}

export async function setSpaceToken(space: string, token: string): Promise<void> {
  const creds = await readCredentials();
  creds[space] = { token };
  await fs.mkdir(AUTH_DIR, { recursive: true });
  await fs.writeFile(CREDENTIALS_FILE, JSON.stringify(creds, null, 2), { mode: 0o600 });
  await fs.chmod(CREDENTIALS_FILE, 0o600).catch(() => {});
}

export async function hasSpaceToken(space: string): Promise<boolean> {
  const creds = await readCredentials();
  return Boolean(creds[space]?.token);
}

export async function removeSpaceToken(space: string): Promise<void> {
  const creds = await readCredentials();
  if (!(space in creds)) return;
  delete creds[space];
  await fs.writeFile(CREDENTIALS_FILE, JSON.stringify(creds, null, 2), { mode: 0o600 });
}

const ASKPASS_SOURCE = `#!/usr/bin/env node
// Generated by server/gitCredentials.ts — do not edit by hand.
// git invokes this as: askpass.mjs "Username for '...': " (or "Password for ...").
// Which space's token to use travels via FOLIO_GIT_SPACE, set by server/git.ts
// on the git child process's own environment for that one call. A one-off
// call with no space yet (server/git.ts's listRemoteBranches, for the
// create-space dialog's branch picker) instead sets FOLIO_ONEOFF_TOKEN
// directly on that one child process's env — never written to
// git-credentials.json, so it's checked first and never touches disk.
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const prompt = process.argv[2] ?? '';
const space = process.env.FOLIO_GIT_SPACE ?? '';
const oneoffToken = process.env.FOLIO_ONEOFF_TOKEN ?? '';

if (oneoffToken) {
  process.stdout.write(/username/i.test(prompt) ? 'x-access-token' : oneoffToken);
  process.exit(0);
}

try {
  const raw = await readFile(path.join(here, 'git-credentials.json'), 'utf8');
  const creds = JSON.parse(raw);
  const token = creds[space]?.token;
  if (token) {
    process.stdout.write(/username/i.test(prompt) ? 'x-access-token' : token);
    process.exit(0);
  }
} catch {
  // fall through to an empty answer below
}
process.stdout.write('');
`;

/** Writes (or re-writes) the askpass helper script and makes it executable. Idempotent — safe to call at every boot. */
export async function ensureAskpassScript(): Promise<string> {
  await fs.mkdir(AUTH_DIR, { recursive: true });
  await fs.writeFile(ASKPASS_SCRIPT, ASKPASS_SOURCE, 'utf8');
  await fs.chmod(ASKPASS_SCRIPT, 0o755);
  return ASKPASS_SCRIPT;
}
